# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33b00abd31fb4725eeefd54479aa3931286161e8e7b18f01735774f3d912155ef14d3f76dec762c65eab1aa59c8c1c070ceba86fedea791d0ab3eef3d0d1ebe6

test:
  secret_key_base: a45ba71bb7d3e4f66d279a5131dfa3c5d9eb12f0d4142eb549b387c403b19d68c3a9b8dd7cb53f9f08c4f61a07946158d1dcea9b4792942162216c159329512b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
